# Generated by Django 5.0.14 on 2025-05-16 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
