# Generated by Django 5.0.14 on 2025-05-23 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_payment_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RunningPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="running_plans_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="running_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunningSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (1, "Lunes"),
                            (2, "Martes"),
                            (3, "Miércoles"),
                            (4, "Jueves"),
                            (5, "Viernes"),
                            (6, "Sábado"),
                            (7, "Domingo"),
                        ]
                    ),
                ),
                (
                    "distance",
                    models.DecimalField(
                        decimal_places=2, help_text="Kilómetros", max_digits=6
                    ),
                ),
                (
                    "time_minutes",
                    models.PositiveIntegerField(help_text="Tiempo total en minutos"),
                ),
                (
                    "time_seconds",
                    models.PositiveIntegerField(help_text="Segundos adicionales"),
                ),
                ("series", models.PositiveIntegerField()),
                (
                    "rest_minutes",
                    models.PositiveIntegerField(help_text="Descanso en minutos"),
                ),
                ("rest_seconds", models.PositiveIntegerField(help_text="y segundos")),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="subscriptions.runningplan",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week"],
            },
        ),
    ]
