# Generated by Django 5.0.14 on 2025-05-23 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_runningplan_runningsegment"),
    ]

    operations = [
        migrations.AddField(
            model_name="runningplan",
            name="week_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="RunningItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (1, "Lunes"),
                            (2, "Martes"),
                            (3, "Miércoles"),
                            (4, "Jueves"),
                            (5, "Viernes"),
                            (6, "Sábado"),
                            (7, "Domingo"),
                        ]
                    ),
                ),
                ("distance_value", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "distance_unit",
                    models.CharField(choices=[("km", "km"), ("m", "m")], max_length=2),
                ),
                ("work_time", models.DurationField(help_text="Formato HH:MM:SS")),
                ("series", models.PositiveIntegerField()),
                ("rest_time", models.DurationField(help_text="Formato HH:MM:SS")),
                ("training_type", models.CharField(blank=True, max_length=100)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="subscriptions.runningplan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan__week_number", "day_of_week"],
            },
        ),
        migrations.DeleteModel(
            name="RunningSegment",
        ),
    ]
